### ISSUE TITLE
Child contract communication

### ISSUE THREAD

**Issue by lightclient** [quilt/ewasm-rt#7]
I've spent some time thinking about the communication pattern and the call stack that we might see for an execution environment that can spawn additional runtimes. The result of this thinking is a hypothesis: I believe that for each child runtime, there should a scoped frame of data for each call. 

The most important thing to keep in this frame is the modifications to underlying multiproof. This is because every modification within a child runtime must be atomically committed with all of its children that execute successfully. If one runtime reverts, all its changes and its children's changes should be dropped. The best way that I can think of modeling this is some sort of diffing mechanism.

The high level of how I think this can be accomplished is by adding a buffer (represented as a hash table) that is accessible from the EE and all its children. If lookups are implemented similarly as cache lookups are, falling to the next level in the case of a miss, we should be able to get away with storing only the changes.

##### `buffer_set(frame: u8, key: Bytes32, value: Bytes32)`
* associates `frame` and `key` to `value`

##### `buffer_get(frame: u8, key: Bytes32) -> Option<Bytes32>`
* retrieves the associated value for `frame` and `key`
* returns `None` if not set

##### `buffer_merge(frame_1: u8, frame_2: u8) -> Bool`
* merges the key-value pairs of the two namespaces
* conflicts are always won by `frame_2`

##### `buffer_clear(frame: u8) -> Bool`
* clears all keys related to `frame`

### Context

The other important aspect to keep relative to the current execution frame is the call's context. This includes things like the call's `sender`, `data`, `target`, etc. These values can be the initial data given to the child runtime (like block data is for the parent EE) and these individual values can be accessible via special, dynamically-linked functions. Trust can be established and integrity can maintained by only using the output of these functions as the input for privileged operations (e.g. `msg.sender` of a new call should come from the `msg_destination()` function).

##### `msg_sender() -> Address`
* fetches the input data if it hasn't already been loaded
* returns the address of the call's sender

##### `msg_destination() -> Address`
* fetches the input data if it hasn't already been loaded
* returns the address of the call's destination

##### `msg_data() -> Vec<u8>`
* fetches the input data if it hasn't already been loaded
* return the input data for the transaction

##### `load(index: u256) -> Bytes32`
* fetches the input data if it hasn't already been loaded
* ensures `index` is under the executing contracts state tree
* returns the 32 byte value corresponding to `index` from the highest id'd `ctx`

##### `store(index: u256, value: Bytes32) -> Result<()>`
* fetches the input data if it hasn't already been loaded
* ensures `index` is under the executing contracts state tree
* sets the value of `index` to `value`
* returns a `Result`

##### `call_contract(address: Address, data: Vec<u8>) -> Result<()>`
* fetches the input data if it hasn't already been loaded
* loads the code for contract at `address`
* sets the `id` to the current `id + 1`
* constructs the coresponding `Message` for the call
* calls the raw host function to execute code
* calls the merge host function on `[id, id + 1]` if the call succeeds

### Questions to answer
* Does this communication format even make sense?
* Which is more efficient, copying the entire multiproof for every frame or looking up at each intermediate level until a hit?
* Is it more efficient to merge the buffer natively in the client or within the webassembly binary?

**Comment by lightclient** [comment]
For now, I'm going to direct my focus to implementing the new host functions. The dynamic host functions can be written statically in the child contracts for now (since most of the time, I trust myself).

**Comment by SamWilsn** [comment]
## Design

My first instinct is to compare this chain of cancelable contracts to transactions and sub-transactions in the database world. I am about as far from an expert in database design as you can get, but from a quick google there seem to be two approaches for implementing transactions: [shadow paging](https://en.wikipedia.org/wiki/Shadow_paging) and [write-ahead-logging](https://en.wikipedia.org/wiki/Write-ahead_logging). The approach you're describing seems a lot like shadow paging. Looking into write-ahead-logging as an alternative might be worthwhile.

## Implementation

It wasn't immediately clear when reading that the "Context" section lists functions provided *by an EE* to callees, and "New host functions" are provided *to the EE*.

In other words, the functions in "Context" have to be implemented on top of the host functions.

### Host Functions

- Since buffers in this proposal are actually maps, I'd rename everything to map_*.
- In `buffer_merge`, call the arguments `target` and `other` to make it clear that keys in `target` are overwritten by keys in `other`. Are the values in `other` cleared?
- In `buffer_merge`, what does the return value represent?
- How does one unset a key, and how does that interact with `buffer_merge`? `buffer_set` with all zeroes? If so, `buffer_get` shouldn't return an `Option`.
- What is the rationale behind providing a host implementation of maps, instead of implementing them in WASM?

### Context

- Where does the current id get stored by the EE?
- How do functions implemented by the EE know which map they're associated with?
